### ISSUE TITLE
Add support for QDataStream::Qt_5_4

### ISSUE THREAD

**Issue by ftl** [k0swe/wsjtx-go#39]
QDataStream::Qt_5_4 is used by newer versions of WSJT-X (see [NetworkMessage.hpp](https://sourceforge.net/p/wsjt/wsjtx/ci/master/tree/Network/NetworkMessage.hpp#l74)). The differences between QDataStream::Qt_5_2 and QDataStream::Qt_5_4 are marginal and not relevant, since WSJT-X does not use any of the changed data types.

**Comment by xylo04** [comment]
Released in https://github.com/k0swe/wsjtx-go/releases/tag/v4.1.0
